version: 2

models:
  - name: fct_ingresos
    columns:
      - name: organica_id
      - name: funcional_id
      - name: economica_id
      - name: financiacion_id
      - name: date_day
      - name: importe
  - name: fct_gastos
    columns:
      - name: organica_id
      - name: economica_id
      - name: financiacion_id
      - name: date_day
      - name: importe

